### ISSUE TITLE
TopBar 제목을 클릭해도 mainPage로 돌아가지 않는 문제

### ISSUE THREAD

**Issue by ABlued** [NikkoNaekko/NikkoNaekko#14]
# issue 
<br>
<br>

![화면 캡처 2021-09-24 084717](https://user-images.githubusercontent.com/53801395/134597970-3503dbfc-fb68-451a-b5d6-f172e9142b75.jpg)
<br>
TopBar에 제목인 "니꼬내꼬"를 클릭하면 history.push('/main')으로 인하여 MainPage로 돌아가야하는데 아무런 반응이 없다.   
<br>

![화면 캡처 2021-09-24 084535](https://user-images.githubusercontent.com/53801395/134598044-e9a63b59-aa75-43f7-b673-f70f4ac41b06.jpg)
<br>
# Cause 
검색바가 나타나지 않는 상태에서도 공간을 차지하여 니꼬내꼬의 영역을 덮어버리게 되어 니꼬내꼬의 이벤트를 차단하게 된다. 
<br>
# solution 
검색바가 나타나지 않을 때는 화면을 차지하지 않게 만들어야 한다.
<br>

**Comment by Jkey-u** [comment]
2021.09.24 Ryu [ TopBar 로고를 클릭해도 mainPage로 돌아가지 않는 문제 해결 ]
